# Generated by Django 4.2 on 2023-04-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='age',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='waist',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterUniqueTogether(
            name='measurement',
            unique_together={('height', 'age', 'weight')},
        ),
    ]
