# Generated by Django 4.2 on 2023-04-22 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_measurement_age_alter_measurement_height_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='measurement',
            unique_together={('height', 'age', 'weight', 'waist')},
        ),
    ]
